# Generated by Django 5.1.2 on 2024-10-26 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='total',
            new_name='precio_total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='correo',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=10),
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
