# Generated by Django 5.1.2 on 2024-10-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_total_pedido_precio_total_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
    ]
