# Generated by Django 5.1.2 on 2024-10-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
